### ISSUE TITLE
get_nchar.R issue

### ISSUE THREAD

**Issue by georod** [eugejoh/pgtools#10]
Hi Eugene. The get_nchar.R was given me this error:

```> rlang::last_error()
<error/purrr_error_bad_element_vector>
Result 3 must be a single string, not a character vector of length 2
Backtrace:
  1. base::source(.paths[5], echo = TRUE, max.deparse.length = 150)
  8. purrr:::stop_bad_element_vector(...)
  9. purrr:::stop_bad_vector(...)
 10. purrr:::stop_bad_type(...)
 ```

I fixed the issue by modifying function(y) at line 47.  If you allow me to contribute I can share my patch. Thanks.

**Comment by georod** [comment]
Also, pg_fields.R seems not to handle integer64 well.  It does not assign a data type ("not assigned").  I also managed to patch it up with this in line 52:

`dplyr::if_else(type == "integer64", "bigint", ...`

I can share this patch.  Thanks.

**Comment by eugejoh** [comment]
Hi Peter, thanks for identifying these issues! I've been away from these repos for a while so I will review the changes. Also thanks for creating the PR
